### ISSUE TITLE
[FEATURE] Improve the Readme of this Project

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/HTML-MarkDown-Converter#1]
If you have any **good ideas** on how to improve the readme.md file of this project, we will be happy to know them!

Try to make it **beginner-friendly**, and **concise** and have **good examples** to explain something.

**Comment by Atharv-777** [comment]
hey @prakhartiwari0 shall i work on this?

**Comment by prakhartiwari0** [comment]
> hey @prakhartiwari0 shall i work on this?

Sure @Atharv-777  you can!

**Comment by prakhartiwari0** [comment]
Issue solved in #4 by @Atharv-777
