### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by Hrishi5111998** [prakhartiwari0/HTML-MarkDown-Converter#10]
**Is your feature request related to a problem? Please describe.**
In the readme file there are many occasions were image is not been able to load. for example In **how to contribute section ** there forking should be load but can't ! Please fix it!

**Describe the solution you'd like**
add the image to the location suggested

**Describe alternatives you've considered** (optional)

**Additional context** (optional)
![2023-01-24](https://user-images.githubusercontent.com/115489262/214345645-b23d2353-bdb3-498e-abea-f6b714b222b3.png)

**Comment by prakhartiwari0** [comment]
Hey @Hrishi5111998 I guess it is an issue from your side, the images are being shown: 
![image](https://user-images.githubusercontent.com/65062036/214492109-8b91afb1-25e6-47af-8c4a-9d1d65e1b57b.png)

**Comment by Hrishi5111998** [comment]
sorry about it ! I think my internet connection were not good last night
